/*Editor: Johnson Gao 
 * Date This File Created: 2020-2-2 15:07:14
 * Description Of This Class:
 */
package towerofhanoicalculator;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 * This is the user's control panel.
 *
 * @author Jianqing Gao
 */
public class UserControl extends javax.swing.JFrame
{

    private GFG calculator;
    private Clip clip;

    /**
     * Creates new form UserControl
     */
    public UserControl() //throws LineUnavailableException
    {
        initComponents();
        try
        {
            clip = AudioSystem.getClip();
        } catch (Exception ex)
        {
            Warning.createWarningDialog(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        disksNumberField = new javax.swing.JFormattedTextField();
        calculateButton = new javax.swing.JButton();
        showResultButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        from_rodField = new javax.swing.JTextField();
        aux_rodField = new javax.swing.JTextField();
        to_rodField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        messageField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/towerofhanoicalculator/a3c3684d9afba387276e8e16997c92f3.png"))); // NOI18N

        jLabel2.setText("Please enter how many disks to move -->");

        jLabel3.setText("MAX : 30");

        disksNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        disksNumberField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                disksNumberFieldKeyTyped(evt);
            }
        });

        calculateButton.setBackground(new java.awt.Color(0, 255, 0));
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                calculateButtonActionPerformed(evt);
            }
        });

        showResultButton.setBackground(new java.awt.Color(102, 102, 255));
        showResultButton.setText("Show Results");
        showResultButton.setVisible(false);
        showResultButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                showResultButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/towerofhanoicalculator/f2_3.gif"))); // NOI18N

        jLabel5.setText("Names For Columns");

        from_rodField.setText("A");
        from_rodField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                from_rodFieldKeyTyped(evt);
            }
        });

        aux_rodField.setText("B");
        aux_rodField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                aux_rodFieldKeyTyped(evt);
            }
        });

        to_rodField.setText("C");
        to_rodField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                to_rodFieldKeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        messageField.setEditable(false);
        messageField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        messageField.setText("Welcome! Made By Johnson");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(disksNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(from_rodField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aux_rodField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(to_rodField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateButton)
                .addGap(88, 88, 88)
                .addComponent(showResultButton)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageField)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(disksNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(from_rodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aux_rodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(to_rodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(showResultButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateButtonActionPerformed
    {//GEN-HEADEREND:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        playSound(Sounds.CLICK);
        int numberOfThem;
        calculator = new GFG();
        try
        {
            numberOfThem = Integer.parseInt(disksNumberField.getText());
            if (numberOfThem <= 30)
            {
                calculator.towerOfHanoi(numberOfThem, from_rodField.getText(), to_rodField.getText(), aux_rodField.getText());
                showResultButton.setVisible(true);
                messageField.setText("Calculation completed! Click on\"Show Results\" to see your result!");
                playSound(Sounds.DING_DONG);
            } else if (numberOfThem <= 0)
            {
                messageField.setText("Please enter a positive integer.");
                disksNumberField.requestFocus();
            } else
            {
                messageField.setText("Maximun number is 30! Please check your number!");
                disksNumberField.requestFocus();
            }

        } catch (Exception e)
        {
            Warning warning = Warning.createWarningDialog(e);
            warning.setSolution(() ->
            {
                disksNumberField.requestFocus();
            });
            if (e instanceof NumberFormatException)
            {
                messageField.setText("Please enter only integers in the designated field!");
            } else
            {
                messageField.setText("An exception has happened!");
            }

        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        playSound(Sounds.CLICK);
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showResultButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showResultButtonActionPerformed
    {//GEN-HEADEREND:event_showResultButtonActionPerformed
        // TODO add your handling code here:
        playSound(Sounds.CLICK);
        Result result = new Result(calculator);
        result.setVisible(true);
        messageField.setText("Previous result are shown. If you want to redo, enter a new number and click \"calculate\"");
    }//GEN-LAST:event_showResultButtonActionPerformed

    private void disksNumberFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_disksNumberFieldKeyTyped
    {//GEN-HEADEREND:event_disksNumberFieldKeyTyped
        // TODO add your handling code here:
        playSound(Sounds.TYPE);
    }//GEN-LAST:event_disksNumberFieldKeyTyped

    private void from_rodFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_from_rodFieldKeyTyped
    {//GEN-HEADEREND:event_from_rodFieldKeyTyped
        // TODO add your handling code here:
        //playSound(Sounds.TYPE);
    }//GEN-LAST:event_from_rodFieldKeyTyped

    private void aux_rodFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aux_rodFieldKeyTyped
    {//GEN-HEADEREND:event_aux_rodFieldKeyTyped
        // TODO add your handling code here:
        //playSound(Sounds.TYPE);
    }//GEN-LAST:event_aux_rodFieldKeyTyped

    private void to_rodFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_to_rodFieldKeyTyped
    {//GEN-HEADEREND:event_to_rodFieldKeyTyped
        // TODO add your handling code here:
        //playSound(Sounds.TYPE);
    }//GEN-LAST:event_to_rodFieldKeyTyped
//18429329e200993649a7f6d4bc1f5d0f
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UserControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UserControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UserControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UserControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            UserControl control = new UserControl();
            control.getContentPane().setBackground(new Color(255, 255, 204));
            control.setVisible(true);
        });
    }

    public void playSound(String path)
    {
        try
        {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResource(path)));
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex)
        {
            Logger.getLogger(UserControl.class.getName()).log(Level.SEVERE, null, ex);
            Warning.createWarningDialog(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aux_rodField;
    private javax.swing.JButton calculateButton;
    private javax.swing.JFormattedTextField disksNumberField;
    private javax.swing.JTextField from_rodField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField messageField;
    private javax.swing.JButton showResultButton;
    private javax.swing.JTextField to_rodField;
    // End of variables declaration//GEN-END:variables
}
